services:

  django:
    build: .
    Container_name: agendamento
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    
    ports:
      - "8000:8000"

    enviroments:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

    depends_on:
      - postgres

    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    envioroment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volume:
      - postgres:/var/lib/postgresql/